### ISSUE TITLE
NameError: name 'Dataset' is not defined

### ISSUE THREAD

**Issue by SaraiQX** [XuhanLiu/DrugEx#21]
Hi Dr Liu,
Great thanks for the amazing work. I also had to your lecture from Bilili.
So I tried to redo your work, and found an error occurred several times (as below). Could you pls kindly enlighten me a bit about the possible solution?  Thank you and happy new year!
```

# 试运行 python autodl-nas/DrugEx-master/dataset.py

(drugex) root@autodl-container-a64e118552-fa88b88c:~# python autodl-nas/DrugEx-master/dataset.py
Traceback (most recent call last):
  File "autodl-nas/DrugEx-master/dataset.py", line 7, in <module>
    from utils import VocSmiles as Voc
  File "/root/autodl-nas/DrugEx-master/utils/__init__.py", line 5, in <module>
    from .vocab import *
  File "/root/autodl-nas/DrugEx-master/utils/vocab.py", line 303, in <module>
    class TgtData(Dataset):
NameError: name 'Dataset' is not defined
(drugex) root@autodl-container-a64e118552-fa88b88c:~#

# 问题 utils/vocab.py文件中的class TgtData(Dataset):
```
```
Best,
Sarai

**Comment by martin-sicho** [comment]
Hi @SaraiQX, maybe a little late, but you can also try the revamped version of DrugEx we are working on here: https://github.com/CDDLeiden/DrugEx. It should be a bit easier to use and also has some comprehensive tutorials. Let us know if you have any more questions.

**Comment by XuhanLiu** [comment]
Hi @SaraiQX, 

Thanks for having interest with my works. I noticed that TgtData is useless. Therefore I have removed this class. If you want to try the latest version. I strongly recommend you to you intalled version in https://github.com/CDDLeiden/DrugEx as @martin-sicho mentioned. 

Cheers, 

Xuhan
