### ISSUE TITLE
AttributeError: 'int' object has no attribute 'predict_proba'  

### ISSUE THREAD

**Issue by a919224757** [XuhanLiu/DrugEx#5]
when run the agent.py , There was an error and I didn't debug it

Could you give me some advice?  Thank you

Traceback (most recent call last):
  File "agent.py", line 159, in <module>
    main()
  File "agent.py", line 124, in main
    Policy_gradient(agent, environ, explore=explore)
  File "agent.py", line 38, in Policy_gradient
    preds = environ(smiles)
  File "C:\Users\wmy\DL\DrugEx\util.py", line 194, in __call__
    preds = self.clf.predict_proba(fps)[:, 1]
AttributeError: 'int' object has no attribute 'predict_proba'

**Comment by XuhanLiu** [comment]
I guess it is caused by the classification model in your environment. self.clf should by a scikit-learn based machine learning model, not int type. Before you run the "agent.py", you have to train a classification model with Scikit-Learn and dump it in your hard drive and set the 'env_path' as the file path of this model.

**Comment by a919224757** [comment]
> I guess it is caused by the classification model in your environment. self.clf should by a scikit-learn based machine learning model, not int type. Before you run the "agent.py", you have to train a classification model with Scikit-Learn and dump it in your hard drive and set the 'env_path' as the file path of this model.

Thank you!  This is because I generated the wrong .pkg model ! 
One thing I care about is that environ.py could automatically generate a .pkg file yesterday,  but today only generated the cv and ind,  it couldn't generate the .pkg until I changed some code:
    model = RandomForestClassifier(n_estimators=1000, n_jobs=10)
    model.fit(X, y[:, 0])
    joblib.dump(model, out+'.pkg')

its very interteresting......

(It was the use of yesterday's model that emerge the bug.....@_@)
